packages:
  core: !include m5stack_atom_echo.yaml

esphome:
  project:
    name: DoYouHost.M5Stack_Atom_Echo
    version: dev

dashboard_import:
  package_import_url: github://DoYouHost/M5Stack_Atom_Echo/m5stack_atom_echo.yaml@main

improv_serial: