substitutions:
  name: m5stack-atom-echo
  friendly_name: M5Stack Atom Echo
  micro_wake_word_model: okay_nabu  # alexa, hey_jarvis, hey_mycroft are also supported

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  min_version: 2024.9.0

project:
    name: MorganMLGman.M5Stack_Atom_Echo
    version: "1.0.0"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:
  level: DEBUG

wifi:
  reboot_timeout: 10min
  ap:

captive_portal:

api:
  reboot_timeout: 10min

ota:
  - platform: esphome
    id: ota_esphome

dashboard_import:
  package_import_url: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: ESPHome Version
    entity_category: "diagnostic"

  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: "diagnostic"
    ssid:
      name: WiFi SSID
      entity_category: "diagnostic"
    bssid:
      name: WiFi BSSID
      entity_category: "diagnostic"

binary_sensor:
  - platform: status
    name: Status
    device_class: connectivity

sensor:
  - platform: wifi_signal
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    update_interval: 60s
    accuracy_decimals: 0
    icon: mdi:clock-outline
    entity_category: "diagnostic"

  - platform: internal_temperature
    name: "Internal Temperature"

button:
  - platform: shutdown
    name: Shut Down

  - platform: restart
    name: Restart
  
  - platform: safe_mode
    name: Safe Mode

  - platform: factory_reset
    name: Factory Reset