packages:
  core: !include m5stack_atom_echo.yaml

esphome:
  project:
    name: MorganMLGman.M5Stack_Atom_Echo
    version: dev

dashboard_import:
  package_import_url: github://MorganMLGman/M5Stack_Atom_Echo/m5stack_atom_echo.yaml@main


esp32_improv:
  authorizer: none

improv_serial: