title: M5Stack Atom Echo - ESPHome Voice Assistant
description: Compact voice assistant device with wake word detection, LED indicators, and Home Assistant integration. Powered by ESPHome and ESP Web Tools.
theme: jekyll-theme-minimal
