name: Publish Firmware

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: DoYouHost/workflows/.github/workflows/build.yml@main
    with:
      #### Modify below here to match your project ####
      files: |
        m5stack_atom_echo.factory.yaml
      esphome-version: 2025.5.1
      combined-name: M5Stack_Atom_Echo
      #### Modify above here to match your project ####

      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  upload-to-r2:
    if: github.event_name == 'release'
    name: Upload to R2
    needs:
      - build-firmware
    uses: DoYouHost/workflows/.github/workflows/upload-to-r2.yml@main
    with:
      directory: esphome-atom-echo
    secrets: inherit

  upload-to-release:
    name: Upload to Release
    uses: DoYouHost/workflows/.github/workflows/upload-to-gh-release.yml@main
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}

  promote-beta:
    name: Promote to Beta
    if: github.event_name == 'release'
    uses: DoYouHost/workflows/.github/workflows/promote-r2.yml@main
    needs:
      - upload-to-r2
    with:
      version: ${{ github.event.release.tag_name }}
      directory: esphome-atom-echo
      channel: beta
      manifest-filename: manifest-beta.json
    secrets: inherit

  promote-prod:
    name: Promote to Production
    if: github.event_name == 'release' && github.event.release.prerelease == false
    uses: DoYouHost/workflows/.github/workflows/promote-r2.yml@main
    needs:
      - upload-to-r2
    with:
      version: ${{ github.event.release.tag_name }}
      directory: esphome-atom-echo
      channel: production
      manifest-filename: manifest.json
    secrets: inherit
